"""add_users_reports_hierarchy

Revision ID: 4e12ecaaa3e2
Revises: 
Create Date: 2026-06-07 13:16:32.760947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e12ecaaa3e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('creator_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('manager_task_type', sa.String(length=50), nullable=True))
    op.alter_column('tasks', 'goal_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'tasks', 'employees', ['creator_id'], ['id'], ondelete='SET NULL')
    op.add_column('teams', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'teams', 'employees', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'manager_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'goal_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tasks', 'manager_task_type')
    op.drop_column('tasks', 'creator_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###
